#:schema node_modules/wrangler/config-schema.json
name = "saas-admin-template-workflows"
main = "src/index.mts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[vars]
EXAMPLE_VALUE = "example_value"

[[d1_databases]]
binding = "DB"
database_name = "admin-db"
database_id = "b33ea9ff-6aef-4b5c-b3fd-94f25295b08a"

[[workflows]]
binding = "CUSTOMER_WORKFLOW"
class_name = "CustomerWorkflow"
name = "customer_workflow"
